### ISSUE TITLE
Solo Mining with the FIRO Core Wallet QT

### ISSUE THREAD

**Issue by mucsav1977** [firoorg/firominer#8]
Hello,
can anybody tell me what I  must do for mine with firominer solo localhost.
Please give me the cmd.

I write the cmd from this website and from the firo.org.
All not work.
In firo.org is written: https://firo.org/guide/how-to-mine-firo.html
./firominer -P http://firo:firopow@127.0.0.1:8382 --reward-address **YOURFIROADDRESS**

but the firominer not accept --reward-address

Please give me an exact cmd which work.

Thanks

**Comment by justanwar** [comment]
This command is added with v1.1.0, please try that version.
