### ISSUE TITLE
Error: Got invalid Json message

### ISSUE THREAD

**Issue by SamuLibero** [firoorg/firominer#9]
Hi, 

i'm having this problem and I cannot find a solution for it: 

 i 15:39:20 main      Configured pool 127.0.0.1:8382
 i 15:39:20 <unknown> Selected pool 127.0.0.1:8382
 i 15:39:20 <unknown> Established connection to 127.0.0.1:8382
 i 15:39:20 <unknown> Spinning up miners...
cu 15:39:20 cuda-0    Using Pci Id : 01:00.0 Quadro T2000 with Max-Q Design (Compute 7.5) Memory : 4.00 GB
 X 15:39:20 <unknown> Got invalid Json message : * Line 1, Column 1   Syntax error: value, object or array expected.
 m 15:39:25 <unknown> 0:00 A0 0.00 h - cu0 0.00
 m 15:39:30 <unknown> 0:00 A0 0.00 h - cu0 0.00
 m 15:39:35 <unknown> 0:00 A0 0.00 h - cu0 0.00

As soon as I start the bat file, and everything seems to work fine I have this Json Error and then I repetedly get prompted the same line " m 15:39:35 <unknown> 0:00 A0 0.00 h - cu0 0.00"

Which could be the solution? 

Thanks in advance!

**Comment by rbfx4x** [comment]
I have exactly the same issue. I've even tried reformatting the json with quotes or different combinations of brackets. No joy.

**Comment by joelake13** [comment]
@rbfx4x @SamuLibero 

I had the same issue and found the problem. So the Firo site does not explain it well but when you set up the firo.conf file, the user name and password must match the miner.bat file see the example below. I hope this helps you out. 

firo.conf
rpcuser=**MINER**
rpcpassword=**123Password**
rpcport=8382
 @rpcallowip=127.0.0.1
listen=1
server=1
daemon=1

Miner.bat
firominer -P http://**MINER:123Password**@127.0.0.1:8382 --reward-address YOURFIROADDRESS

**Comment by justanwar** [comment]
Thank you for the report. The guide on the site has been updated.

**Comment by joelake13** [comment]
My pleasure
